### ISSUE TITLE
Deal with ajax-filled content

### ISSUE THREAD

**Issue by alchimere** [alchimere/prism-rss#3]
- Add a css selector to wait for
- Use watir to process the javascript

```ruby
#poc
require 'watir'
require 'webdrivers'
browser = Watir::Browser.new :firefox
browser.goto "https://yolo.plop/page-with-ajax-content"
browser.element(css: ".table-responsive").wait_until(&:present?)
browser.html
browser.close
```

We could add an option to set the css selector:

```yaml
url: https://www.ruby-lang.org/en/
author: firetonton
selectors:
  wait_for: "#main #content .post"
  date: "#main #content .post:first-child .post-info"
  title: "head title"
  item: "#main #content .post"
  item_link: "h3 a"
  item_title: "h3 a"
  item_date: ".post-info"
extractors:
  date: "(\\d+ [a-zA-Z]+ \\d+)$"
  item_date: "(\\d+ [a-zA-Z]+ \\d+)$"
```
Or simply wait until all `date`, `title` and `item` selector returns something, like

```ruby
# pseudocode
browser = Watir::Browser.new :firefox
browser.goto "https://yolo.plop/page-with-ajax-content"
# Wait for the three selectors
browser.element(css: selectors.title).wait_until(&:present?)
browser.element(css: selectors.date).wait_until(&:present?)
browser.element(css: selectors.item).wait_until(&:present?)
browser.html
browser.close
```
